// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchRectangle } from "../rules/utils/MatchRectangle";
import type { TextPosition } from "../rules/utils/TextPosition";
import type { TextRange } from "../rules/utils/TextRange";

export interface BracketHighlightBracket {
  text_range: TextRange;
  text_position: TextPosition;
  rectangle: MatchRectangle;
}
