// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BracketHighlightElbow {
  origin_x: number | null;
  origin_x_left_most: boolean;
  bottom_line_bottom: boolean;
}
