// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FunctionParameterWithExplanation {
  name: string;
  explanation: string;
  param_type: string;
}
