// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateNodeExplanationMessage } from "./UpdateNodeExplanationMessage";

export type NodeExplanationEvent = {
  event: "UpdateNodeExplanation";
  payload: UpdateNodeExplanationMessage;
};
