// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionParameterWithExplanation } from "./FunctionParameterWithExplanation";
import type { SwiftCodeBlockKind } from "./SwiftCodeBlockKind";

export interface NodeExplanation {
  summary: string;
  kind: SwiftCodeBlockKind;
  parameters: Array<FunctionParameterWithExplanation> | null;
}
