// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwiftCodeBlockKind =
	| 'Function'
	| 'For'
	| 'If'
	| 'Class'
	| 'Switch'
	| 'While'
	| 'Do'
	| 'Guard';
