// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRange } from "./TextRange";

export interface MatchRange {
  string: Array;
  range: TextRange;
}
