// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalPosition } from "../../geometry/LogicalPosition";
import type { LogicalSize } from "../../geometry/LogicalSize";

export interface MatchRectangle {
  origin: LogicalPosition;
  size: LogicalSize;
}
