// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleName } from "../rules/RuleName";

export interface CoreActivationStatusMessage {
  engine_active: boolean | null;
  active_feature: RuleName | null;
}
