// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreActivationStatusMessage } from "./CoreActivationStatusMessage";
import type { NodeAnnotationClickedMessage } from "./NodeAnnotationClickedMessage";
import type { RefactoringMessage } from "./RefactoringMessage";

export type EventUserInteraction =
  | { event: "CoreActivationStatus"; payload: CoreActivationStatusMessage }
  | { event: "PerformRefactoringOperation"; payload: RefactoringMessage }
  | { event: "DismissRefactoringSuggestion"; payload: RefactoringMessage }
  | { event: "ToggleMainWindow"; payload: boolean }
  | { event: "NodeAnnotationClicked"; payload: NodeAnnotationClickedMessage };
