// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiFeaturesStatusMessage } from "./AiFeaturesStatusMessage";
import type { DismissSuggestionMessage } from "./DismissSuggestionMessage";
import type { NodeAnnotationClickedMessage } from "./NodeAnnotationClickedMessage";
import type { PerformSuggestionMessage } from "./PerformSuggestionMessage";
import type { UpdateSelectedSuggestionMessage } from "./UpdateSelectedSuggestionMessage";

export type EventUserInteraction =
  | { event: "AiFeaturesStatus"; payload: AiFeaturesStatusMessage }
  | { event: "PerformSuggestion"; payload: PerformSuggestionMessage }
  | { event: "DismissSuggestion"; payload: DismissSuggestionMessage }
  | {
    event: "UpdateSelectedSuggestion";
    payload: UpdateSelectedSuggestionMessage;
  }
  | { event: "ToggleMainWindow"; payload: boolean }
  | { event: "NodeAnnotationClicked"; payload: NodeAnnotationClickedMessage };
