// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreActivationStatusMessage } from "./CoreActivationStatusMessage";
import type { SearchQueryMessage } from "./SearchQueryMessage";

export type EventUserInteraction =
  | { event: "SearchQuery"; payload: SearchQueryMessage }
  | { event: "CoreActivationStatus"; payload: CoreActivationStatusMessage }
  | { event: "None" };
