// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UpdateSelectedSuggestionMessage {
  id: string | null;
  editor_window_uid: number;
}
