// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationGroup } from "../code_annotations/AnnotationGroup";
import type { RemoveNodeAnnotationMessage } from "./RemoveNodeAnnotationMessage";
import type { UpdateNodeAnnotationMessage } from "./UpdateNodeAnnotationMessage";

export type AnnotationEvent =
  | { event: "UpdateNodeAnnotation"; payload: UpdateNodeAnnotationMessage }
  | { event: "RemoveNodeAnnotation"; payload: RemoveNodeAnnotationMessage }
  | { event: "AddAnnotationGroup"; payload: AnnotationGroup }
  | { event: "UpdateAnnotationGroup"; payload: AnnotationGroup }
  | { event: "RemoveAnnotationGroup"; payload: string };
