// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationGroup } from "../code_annotations/AnnotationGroup";

export type AnnotationEvent =
  | { event: "AddAnnotationGroup"; payload: AnnotationGroup }
  | { event: "UpdateAnnotationGroup"; payload: AnnotationGroup }
  | { event: "RemoveAnnotationGroup"; payload: string };
