// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoveNodeAnnotationMessage } from "./RemoveNodeAnnotationMessage";
import type { UpdateNodeAnnotationMessage } from "./UpdateNodeAnnotationMessage";

export type NodeAnnotationEvent = {
  event: "UpdateNodeAnnotation";
  payload: UpdateNodeAnnotationMessage;
} | { event: "RemoveNodeAnnotation"; payload: RemoveNodeAnnotationMessage };
