// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalFrame } from "../../geometry/LogicalFrame";

export interface UpdateNodeAnnotationMessage {
  id: string;
  editor_window_uid: number;
  annotation_icon: LogicalFrame | null;
  annotation_codeblock: LogicalFrame | null;
}
