// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationKind } from "./AnnotationKind";
import type { AnnotationShape } from "./AnnotationShape";
import type { ViewportPositioning } from "./ViewportPositioning";

export interface Annotation {
  id: string;
  kind: AnnotationKind;
  position_relative_to_viewport: ViewportPositioning;
  shapes: Array<AnnotationShape>;
}
