// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { FeatureKind } from "./FeatureKind";

export interface AnnotationGroup {
  id: string;
  feature: FeatureKind;
  annotations: Array<Annotation>;
}
