// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationKind } from "./AnnotationKind";
import type { AnnotationShape } from "./AnnotationShape";
import type { VisibleTextRangePositioning } from "./VisibleTextRangePositioning";

export interface Annotation {
  id: string;
  kind: AnnotationKind;
  char_index: number;
  position_relative_to_viewport: VisibleTextRangePositioning;
  shapes: Array<AnnotationShape>;
}
