// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalPosition } from "./LogicalPosition";
import type { LogicalSize } from "./LogicalSize";

export interface LogicalFrame {
  origin: LogicalPosition;
  size: LogicalSize;
}
