// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchRectangle } from "../../rules/utils/MatchRectangle";

export interface CodeAnnotationMessage {
  id: string;
  annotation_icon: MatchRectangle | null;
  annotation_codeblock: MatchRectangle | null;
}
