// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocsGeneratedMessage } from "./DocsGeneratedMessage";
import type { RemoveCodeAnnotationMessage } from "./RemoveCodeAnnotationMessage";
import type { UpdateCodeAnnotationMessage } from "./UpdateCodeAnnotationMessage";

export type EventDocsGeneration =
  | { event: "UpdateCodeAnnotation"; payload: UpdateCodeAnnotationMessage }
  | { event: "RemoveCodeAnnotation"; payload: RemoveCodeAnnotationMessage }
  | { event: "DocsGenerated"; payload: DocsGeneratedMessage };
