// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeAnnotationMessage } from "./CodeAnnotationMessage";
import type { DocsGeneratedMessage } from "./DocsGeneratedMessage";
import type { RemoveCodeAnnotationMessage } from "./RemoveCodeAnnotationMessage";

export type EventDocsGeneration =
  | { event: "UpdateCodeAnnotation"; payload: CodeAnnotationMessage }
  | { event: "RemoveCodeAnnotation"; payload: RemoveCodeAnnotationMessage }
  | { event: "DocsGenerated"; payload: DocsGeneratedMessage };
