// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalFrame } from "../../geometry/LogicalFrame";
import type { NodeExplanation } from "./NodeExplanation";

export interface NodeExplanationFetchedMessage {
  explanation: NodeExplanation;
  name: string | null;
  window_uid: number;
  annotation_frame: LogicalFrame | null;
}
