// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeExplanation } from "./NodeExplanation";

export interface NodeExplanationFetchedMessage {
  explanation: NodeExplanation;
  name: string;
}
