// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BracketHighlightBracket } from "./BracketHighlightBracket";

export interface BracketHighlightBracketPair {
  first: BracketHighlightBracket | null;
  last: BracketHighlightBracket | null;
}
