// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalFrame } from "../../geometry/LogicalFrame";

export interface BracketHighlightBoxPair {
  opening_bracket: LogicalFrame | null;
  closing_bracket: LogicalFrame | null;
}
