// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BracketHighlightBracketPair } from "./BracketHighlightBracketPair";
import type { BracketHighlightElbow } from "./BracketHighlightElbow";

export interface BracketHighlightResults {
  lines: BracketHighlightBracketPair;
  elbow: BracketHighlightElbow | null;
  boxes: BracketHighlightBracketPair;
}
