// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BracketHighlightBoxPair } from "./BracketHighlightBoxPair";
import type { BracketHighlightLines } from "./BracketHighlightLines";

export interface BracketHighlightResults {
  lines: BracketHighlightLines;
  boxes: BracketHighlightBoxPair;
}
