// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalPosition } from "../../geometry/LogicalPosition";

export interface BracketHighlightElbow {
  origin: LogicalPosition | null;
  origin_x_left_most: boolean;
  bottom_line_top: boolean;
}


lines{
  start : LogicalFrame,
  end: LogicalFrame
  elbow: Option<Elbow>,
}

enum Elbow {
  LeftMost,
  Position(LogicalPosition)
}