// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Elbow } from "./Elbow";
import type { LogicalPosition } from "../../geometry/LogicalPosition";

export interface BracketHighlightLines {
  start: LogicalPosition | null;
  end: LogicalPosition | null;
  elbow: Elbow | null;
}
