// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalPosition } from '../../geometry/LogicalPosition';

export type Elbow =
	| { KnownElbow: LogicalPosition }
	| {
			EstimatedElbowOffset: number;
	  };
