// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChannelList =
  | "AXEventApp"
  | "AXEventXcode"
  | "BracketHighlightResults"
  | "EventInputDevice"
  | "EventRuleExecutionState"
  | "EventTrackingAreas"
  | "EventUserInteractions"
  | "EventWindowControls"
  | "EventDocsGeneration"
  | "RuleResults"
  | "EventViewport";
