// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DarkModeUpdateMessage } from "./DarkModeUpdateMessage";
import type { HideAppWindowMessage } from "./HideAppWindowMessage";
import type { ShowAppWindowMessage } from "./ShowAppWindowMessage";
import type { TrackingAreaClickedMessage } from "./TrackingAreaClickedMessage";
import type { TrackingAreaClickedOutsideMessage } from "./TrackingAreaClickedOutsideMessage";
import type { TrackingAreaEnteredMessage } from "./TrackingAreaEnteredMessage";
import type { TrackingAreaExitedMessage } from "./TrackingAreaExitedMessage";
import type { TrackingAreaMouseOverMessage } from "./TrackingAreaMouseOverMessage";
import type { UpdateAppWindowMessage } from "./UpdateAppWindowMessage";

export type EventWindowControls =
  | { event: "TrackingAreaClicked"; payload: TrackingAreaClickedMessage }
  | {
    event: "TrackingAreaClickedOutside";
    payload: TrackingAreaClickedOutsideMessage;
  }
  | { event: "TrackingAreaEntered"; payload: TrackingAreaEnteredMessage }
  | { event: "TrackingAreaExited"; payload: TrackingAreaExitedMessage }
  | { event: "TrackingAreaMouseOver"; payload: TrackingAreaMouseOverMessage }
  | { event: "AppWindowHide"; payload: HideAppWindowMessage }
  | { event: "AppWindowShow"; payload: ShowAppWindowMessage }
  | { event: "AppWindowUpdate"; payload: UpdateAppWindowMessage }
  | { event: "DarkModeUpdate"; payload: DarkModeUpdateMessage };
