// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HideAppWindowMessage } from './HideAppWindowMessage';
import type { LogicalFrame } from '../geometry/LogicalFrame';
import type { ShowAppWindowMessage } from './ShowAppWindowMessage';
import type { TrackingAreaClickedMessage } from './TrackingAreaClickedMessage';
import type { TrackingAreaEnteredMessage } from './TrackingAreaEnteredMessage';
import type { TrackingAreaExitedMessage } from './TrackingAreaExitedMessage';

export type EventWindowControls =
	| { event: 'TrackingAreaClicked'; payload: TrackingAreaClickedMessage }
	| { event: 'TrackingAreaEntered'; payload: TrackingAreaEnteredMessage }
	| { event: 'TrackingAreaExited'; payload: TrackingAreaExitedMessage }
	| { event: 'AppWindowHide'; payload: HideAppWindowMessage }
	| { event: 'AppWindowShow'; payload: ShowAppWindowMessage }
	| { event: 'CodeOverlayDimensionsUpdate'; payload: LogicalFrame };
