// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppWindow } from "../AppWindow";

export interface HideAppWindowMessage {
  app_windows: Array<AppWindow>;
}
