// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppWindow } from "../AppWindow";
import type { LogicalFrame } from "../geometry/LogicalFrame";
import type { LogicalPosition } from "../geometry/LogicalPosition";

export interface ShowAppWindowMessage {
  app_windows: Array<AppWindow>;
  editor_textarea: LogicalFrame;
  widget_position: LogicalPosition | null;
  explain_window_anchor: LogicalFrame | null;
  monitor: LogicalFrame;
}
