// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppWindow } from "../AppWindow";

export interface TrackingAreaExitedMessage {
  id: string;
  window_uid: number;
  app_window: AppWindow;
  duration_ms: bigint;
}
