// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleMatchCategory } from "../rules/utils/RuleMatchCategory";

export interface TrackingAreaEnteredMessage {
  id: string;
  category: RuleMatchCategory;
}
