// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppWindow } from "../AppWindow";
import type { LogicalPosition } from "../geometry/LogicalPosition";

export interface TrackingAreaClickedMessage {
  id: string;
  window_uid: number;
  app_window: AppWindow;
  mouse_position: LogicalPosition;
  duration_ms: bigint;
}
