// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleMatchCategory } from "./utils/RuleMatchCategory";

export interface RuleMatchProps {
  identifier: string;
  description: string;
  category: RuleMatchCategory;
}
