// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalFrame } from "../geometry/LogicalFrame";
import type { MatchRange } from "./utils/MatchRange";
import type { RuleMatchProps } from "./RuleMatchProps";
import type { RuleName } from "./RuleName";

export interface RuleMatch {
  id: string;
  match_range: MatchRange;
  line_matches: Array<[MatchRange, Array]>;
  rectangles: Array<LogicalFrame>;
  rule_name: RuleName;
  match_properties: RuleMatchProps;
}
