// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleMatch } from "./RuleMatch";
import type { RuleType } from "./RuleType";

export interface RuleResults {
  rule: RuleType;
  results: Array<RuleMatch>;
}
