// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchRange } from "./utils/MatchRange";
import type { MatchRectangle } from "./utils/MatchRectangle";

export interface RuleMatch {
  match_range: MatchRange;
  line_matches: Array<[MatchRange, Array]>;
  rectangles: Array<MatchRectangle>;
}
