// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleMatch } from "./RuleMatch";
import type { RuleName } from "./RuleName";

export interface RuleResults {
  rule: RuleName;
  results: Array<RuleMatch>;
}
