// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalFrame } from "../geometry/LogicalFrame";

export interface CodeOverlayDimensionsUpdateMessage {
  code_viewport_rect: LogicalFrame;
  code_document_rect: LogicalFrame;
}
