// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FERefactoringSuggestion {
  new_text_content_string: string | null;
  old_text_content_string: string | null;
  new_complexity: number;
  prev_complexity: number;
  main_function_name: string | null;
}
