// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateRefactoringSuggestionsMessage } from "./UpdateRefactoringSuggestionsMessage";

export type RefactoringEvent = {
  event: "UpdateRefactoringSuggestions";
  payload: UpdateRefactoringSuggestionsMessage;
};
