// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactoringKind } from "./RefactoringKind";

export interface RefactoringOperation {
  id: string;
  new_text_content_string: string;
  old_text_content_string: string;
  kind: RefactoringKind;
}
