// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FERefactoringSuggestion } from "./FERefactoringSuggestion";

export interface ReplaceSuggestionsMessage {
  suggestions: Record<number, Record<string, FERefactoringSuggestion>>;
}
