// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplaceSuggestionsMessage } from "./ReplaceSuggestionsMessage";

export type SuggestionEvent = {
  event: "ReplaceSuggestions";
  payload: ReplaceSuggestionsMessage;
};
