// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddAndRemoveSuggestionsMessage } from "./AddAndRemoveSuggestionsMessage";
import type { RemoveSuggestionMessage } from "./RemoveSuggestionMessage";
import type { UpdateSuggestionMessage } from "./UpdateSuggestionMessage";

export type SuggestionEvent = {
  event: "UpdateSuggestion";
  payload: UpdateSuggestionMessage;
} | {
  event: "AddAndRemoveSuggestions";
  payload: AddAndRemoveSuggestionsMessage;
} | { event: "RemoveSuggestion"; payload: RemoveSuggestionMessage };
