// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateSuggestionsMessage } from "./UpdateSuggestionsMessage";

export type SuggestionEvent = {
  event: "UpdateSuggestions";
  payload: UpdateSuggestionsMessage;
};
