// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefactoringOperation } from "./RefactoringOperation";

export interface UpdateSuggestionsMessage {
  suggestions: Array<RefactoringOperation>;
}
