// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventRuleExecutionState =
  | { event: "SwiftFormatFinished"; payload: null }
  | { event: "SwiftFormatFailed"; payload: null }
  | { event: "DocsGenerationStarted"; payload: null }
  | { event: "DocsGenerationFinished"; payload: null };
