// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeExplanationFetchedMessage } from "../NodeExplanationFetchedMessage";

export type EventRuleExecutionState =
  | { event: "SwiftFormatFinished"; payload: null }
  | { event: "SwiftFormatFailed"; payload: null }
  | { event: "NodeExplanationStarted"; payload: null }
  | { event: "NodeExplanationFailed"; payload: null }
  | { event: "NodeExplanationFetched"; payload: NodeExplanationFetchedMessage };
