// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeExplanationFetchedMessage } from "../features/docs_generation/NodeExplanationFetchedMessage";

export type EventRuleExecutionState =
  | { event: "SwiftFormatFinished"; payload: null }
  | { event: "SwiftFormatFailed"; payload: null }
  | { event: "DocsGenerationStarted"; payload: null }
  | { event: "DocsGenerationFailed"; payload: null }
  | { event: "DocsGenerationFinished"; payload: null }
  | { event: "NodeExplanationFetched"; payload: NodeExplanationFetchedMessage };
