// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalFrame } from "../../geometry/LogicalFrame";

export interface ViewportProperties {
  dimensions: LogicalFrame;
  annotation_section: LogicalFrame | null;
  code_section: LogicalFrame | null;
}
