// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeDocumentFrameProperties } from "./CodeDocumentFrameProperties";
import type { ViewportProperties } from "./ViewportProperties";

export interface ViewportPropertiesUpdateMessage {
  viewport_properties: ViewportProperties;
  code_document_frame_properties: CodeDocumentFrameProperties;
}
